spring:
  application:
    name: fastchat

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: ${GROQ_BASE_URL:https://api.groq.com/openai}
      chat:
        options:
          model: ${GROQ_MODEL:llama-3.3-70b-versatile}
          temperature: ${TEMPERATURE:0.2}

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: WARN
